# Generated by Django 2.2.3 on 2019-07-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Bags', 'Bags'), ('Keychains', 'Keychains'), ('Bookmarks', 'Bookmarks'), ('Paperweights', 'Paperweights'), ('Greetings Cards', 'Greetings Cards'), ('Candles', 'Candles'), ('Jewellery', 'Jewellery'), ('Others', 'Others')], default='others', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=2000.0, max_digits=10)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
    ]
